run:
  timeout: 5m
  go: "1.21"
  modules-download-mode: readonly

linters-settings:
  gocyclo:
    min-complexity: 15
  misspell:
    locale: US
  lll:
    line-length: 140

linters:
  disable-all: true
  enable:
    # 基本检查
    - gofmt
    - govet
    - gosimple
    - staticcheck
    - ineffassign
    - unused
    - errcheck
    - misspell

issues:
  exclude-rules:
    - path: _test\.go
      linters:
        - gocyclo
        - gosec
    - path: internal/code/
      linters:
        - gosec # AI 代码生成模块可能有安全相关的误报
    - path: cmd/
      linters:
        - gosec # 命令行工具可能有权限相关的误报

  max-issues-per-linter: 0
  max-same-issues: 0
