language: go

go:
  - "1.21"

os:
  - linux

dist: xenial

# 缓存模块以加速构建
cache:
  directories:
    - $HOME/.cache/go-build
    - $GOPATH/pkg/mod

# 环境变量
env:
  - GO111MODULE=on

# 构建前的准备工作
before_install:
  - go version
  - echo $HOME
  - echo $GOPATH
  - echo $GOROOT
  - which go

# 安装依赖
install:
  - go mod download
  - go mod verify
  - go install golang.org/x/tools/cmd/goimports@latest
  - go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

# 构建脚本
script:
  # 1. 编译
  - echo "Building project..."
  - make build
  
  # 2. 静态检查
  - echo "Running static analysis..."
  - golangci-lint run ./...
  
  # 3. 格式检查
  - echo "Checking code format..."
  - test -z "$(goimports -l .)"
  
  # 4. 单元测试
  - echo "Running unit tests..."
  - make test
  - go test -race -coverprofile=coverage.txt -covermode=atomic ./...

# 构建成功后的操作
after_success:
  - bash <(curl -s https://codecov.io/bash)

# 通知设置
notifications:
  email:
    on_success: change
    on_failure: always