server:
  port: 8888
  webhook_secret: "1234567890"

github:
  # 可选：保留 PAT 作为回退方案
  token: "ghp_your_personal_access_token"
  
  # GitHub App 配置 / GitHub App Configuration
  app:
    app_id: 1032243
    
    # 私钥配置（三种方式，按优先级顺序）/ Private key configuration (3 methods, in priority order):
    
    # 方式1：文件路径（推荐，最高优先级）/ Method 1: File path (recommended, highest priority)
    private_key_path: "/Users/xxxxx.private-key.pem"
    
    # 方式2：环境变量名（中等优先级）/ Method 2: Environment variable name (medium priority)
    # private_key_env: "GITHUB_APP_PRIVATE_KEY"
    
    # 方式3：直接内容（最低优先级，生产环境不推荐）/ Method 3: Direct content (lowest priority, not recommended for production)
    # private_key: |
    #   -----BEGIN RSA PRIVATE KEY-----
    #   MIIEpAIBAAKCAQEA...
    #   -----END RSA PRIVATE KEY-----
  
  # 认证模式（可选）
  auth_mode: "token"  # auto（默认）| app | token

workspace:
  base_dir: "/tmp/codeagent"
  cleanup_after: "24h"

claude:
  # api_key: 通过 --claude-api-key 参数或 CLAUDE_API_KEY 环境变量设置
  container_image: "goplusorg/codeagent:v0.4"
  timeout: "30m"
  interactive: false

docker:
  socket: "unix:///var/run/docker.sock"
  network: "bridge"

gemini:
  container_image: "goplusorg/codeagent:v0.4"
  timeout: "30m"
