server:
  port: 8888
  webhook_secret: "1234567890"

github:
  #token: "1234567890"
  webhook_url: "http://localhost:8888/hook"
  
  # GitHub App 配置
  app:
    app_id: 1032243  # GitHub App ID (必填)
    private_key_path: "/Users/wangcheng/go/src/codeagent/cmd/server/wangtestapp.2025-08-12.private-key.pem"  # GitHub App Private Key 文件路径
    # 或者通过环境变量指定: private_key_env: "GITHUB_APP_PRIVATE_KEY"
    # 或者直接配置: private_key: "-----BEGIN RSA PRIVATE KEY-----..."

workspace:
  base_dir: "/Users/jicarl/codeagent"
  cleanup_after: "24h"

claude:
  # api_key: 通过 --claude-api-key 参数或 CLAUDE_API_KEY 环境变量设置
  container_image: "goplusorg/codeagent:v0.4"
  timeout: "30m"
  interactive: false

docker:
  socket: "unix:///var/run/docker.sock"
  network: "bridge"

gemini:
  container_image: "goplusorg/codeagent:v0.4"
  timeout: "30m"
